version: "3"
services:
  api_service:
    image: node:16
    container_name: stateful_counter_api
    volumes:
      - ./node_modules:/node_modules
      - ./api:/api
      - ./tsconfig.json:/tsconfig.json
      - ./package.json:/package.json
    ports:
      - "3001:3001"
    working_dir: /
    command: npm run backend
    env_file: .env.development

  mongodb:
    image: mongo:5
    container_name: stateful_counter_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password 
